### PR TITLE
Issue105: add `infIsNA` 

### PR DESCRIPTION
**Pull request by cvanderaa**
Added a new feature, `infIsNA`, that replaces infinite values in one or more assays with `NA`. This was suggested in issue #105.

### CODE REVIEW

**Comment by lgatto** [comment]
I am wondering if we wouldn't need a `infIsNA,SummarizedExperiment,integer` method for when a `SummarizedExperiment` object has multiple assays. I know this should never be the case for `QFeatures` object, and this that the integer would by default always be 1, but it would make sense to be able to use the method more widely with `SummarizedExperiment` objects.

This actually probably also applies to many other methods: `zeroIsNA`, ...

**Comment by cvanderaa** [comment]
This could indeed be added but then I would also add the signatures `infIsNA,SummarizedExperiment,character`?

**Comment by lgatto** [comment]
Do assays of a `SummarizedExperiment` have to be named? If not, then I would prioritise the integer for all the functions we have, and only add the character methods either if we identify a need or if it matches best practice.

**Comment by cvanderaa** [comment]
They don't have to be named.

**Comment by cvanderaa** [comment]
I realize there is an error inn the CI check: `dist: trusty is no longer supported for language: r`. Should we upgrade the `dist` to `xenial`?

**Comment by lgatto** [comment]
I would suggest to move to github actions: see the [`scp/.github`](https://github.com/UCLouvain-CBIO/scp/tree/master/.github) directory for details.

**Comment by cvanderaa** [comment]
I replaced the `yml` files to enable GitHub actions, but since nothing is happening I guess we have to add `actions-user` as a contributor. Or am I missing something else?

**Comment by lgatto** [comment]
May be it needs to get merged to master for the actions to kick in?

**Comment by cvanderaa** [comment]
Indeed thanks!

**Pull request merged**
