### PR TITLE
Implmented an updateObject() method for QFeatures objects (issue #152)

### PR DESCRIPTION
**Pull request by cvanderaa**
This is my attempt to solve the updateObject() issue #152.

Although everything seems to work, I'm not 100% convinced of the implementation: https://github.com/cvanderaa/QFeatures/blob/a3550c0c0251766d1bffcb564eaadb0b95cd4151/R/QFeatures-class.R#L707-L722

Converting to and from an `MAE` is not elegant to me. An alternative I see is to pass the assayLinks as a `...` in `MultiAssayExperiment::updateObject()`, but that is not currently available on their side. I could ask Marcel Ramos for advice. What do you think?

PS: I realized I forgot to push a small change in the plot parameters. I believe this minor tweak does not deserve attention.

### CODE REVIEW

**Comment by lgatto** [comment]
Does `callNextMethod()` trigger a call to `validObject()`? Otherwise, you could do 

```r
al <- object@assayLinks
object <- callNextMethod()
object@assayLinks <- al
```
because I agree that converting back and forward isn't great. 

I would ask on slack, in the same thread.

**Comment by cvanderaa** [comment]
>Does callNextMethod() trigger a call to validObject()? 

Yes it looks like so... Could it be it is automatically triggered upon creation of the object with `new` ? https://github.com/waldronlab/MultiAssayExperiment/blob/4db4d7df99a4bc1cc209e9e7f36180235f1572d5/R/MultiAssayExperiment-class.R#L792-L805  

I tried the code you suggest, but it leads to the same initial error about wrong AssayLinks. That's why I would like to pass `al` as an argument to 
`object <- callNextMethod()`. My guess would be to add `...` at this line so that we can pass our desired slots:  https://github.com/waldronlab/MultiAssayExperiment/blob/4db4d7df99a4bc1cc209e9e7f36180235f1572d5/R/MultiAssayExperiment-class.R#L806
This would allow to call: 
```r
object <- callNextMethod(object, assayLinks = al, ..., verbose = verbose)
```
and avoid converting `object`. But this would require a change in `MAE`. I will ask on slack.

**Comment by lgatto** [comment]
We don't want any change in `MAE`. 

Another option could be to call `updateObject(object, objclass = "MultiAssayExperiment")` to update the `MAE` part of our object, and then construct a new `QFeatures` and add the missing assay link.

**Comment by cvanderaa** [comment]
I agree with you! I have modified the implementation using `objclass = "MultiAssayExperiment"`, it looks cleaner to me now! I'm good for the merge, unless you have additional suggestions.

**Comment by lgatto** [comment]
Happy to hear this works. You might still check with the experts on Slack, to see what they suggest.

**Comment by cvanderaa** [comment]
I refactored the method based on a discussion on the Bioc Slack. I also added `updateObject()` methods for `AssayLinks` and `AssaLink` objects. The 2 methods are currently very simple and serve rather as backbone for later class changes that may occur.

**Pull request merged**
