### PR TITLE
fix: allow subsetting of 'Features' objects containing 'SingleCellExperiment' assays

### PR DESCRIPTION
**Pull request by cvanderaa**
see [issue 273](https://github.com/waldronlab/MultiAssayExperiment/issues/276) in
'MultiAssayExperiment' for background

### CODE REVIEW

**Comment by cvanderaa** [comment]
Wait before merging, it seems I inserted a bug...

**Comment by cvanderaa** [comment]
In my opinion, the `subsetByFeature` has a strange behavior that causes the latest commit to break. See here (tested with the version of `Features` before ea8185d):
```r
data("feat1")
feat1 <- aggregateFeatures(feat1, 1, fcol = "Sequence", 
                           name = "peptides", fun = colMedians)
feat1 <- aggregateFeatures(feat1, 2, fcol = "Protein", 
                           name = "proteins", fun = colMedians)

names(feat1)
## [1] "psms"     "peptides" "proteins"
names(feat1["ProtA"])
## [1] "proteins" "peptides" "psms"    
```
@lgatto, don't you think subsetting features should preserve the assay ordering? 

**Explanation of the error:** The last commit replaces `expts <- experiments(x)[featurename_list]` with `expts <- experiments(x[featurename_list, ])`. The former subsets the experiments according to the ordering of the names in `featurename_list`, the latter subsets the experiments from the list but keeping the ordering of the assays in `x`. `AssayLinks` are subset according to the ordering in `featurename_list`. Hence in the last commit, the `AssayLinks` object is not ordered as the assays in `x`. This is detected as faulty by the `validObject`. So the solution is to either reorder the assays (lose the original assay ordering) or reorder the `AssayLinks` (preserve the original assay ordering)

**Comment by lgatto** [comment]
@cvanderaa as you can see, that change lead to some unit tests failing. Could you look into this and identify why the tests now fail.

**Comment by cvanderaa** [comment]
**Warning**: the unit tests will fail when PR #74 and PR #77 will be both merged into `master`. This is because the reordering discussed [above](https://github.com/rformassspectrometry/Features/pull/74#issuecomment-633926970) changes the expected output values in `test_subsetByFeatures.R`.

**Pull request merged**
